### ISSUE TITLE
关于异常处理

### ISSUE THREAD

**Issue by heimanba** [devsapp/api-gateway#14]
### preCheck
- 校验必填参数
![image](https://user-images.githubusercontent.com/5129967/187716050-b7a7f107-045f-43d9-b9b0-cf3ff01ba65d.png)
```
throw new core.CatchableError('xxx');
```
- 是否存在API冲突。
  - 冲突的话: 明显提示 冲突的内容。直接 终止
  ```
     throw new core.CatchableError('xxx');
  ```
  - 没有冲突，直接部署
-  控制台有修改
![image](https://user-images.githubusercontent.com/5129967/187749387-d860c38c-593e-4279-bd1d-776b44d43156.png)
![image](https://user-images.githubusercontent.com/5129967/187749426-0ab8f53e-e298-43f7-b3be-238129374d15.png)

 

### 执行过程中，给出友好提示
-  配额5个，异常时候，友好提示
```
throw new core.CatchableError('xxx');
```

**Comment by wizardAEI** [comment]
1 4 做了初步实现

**Comment by wizardAEI** [comment]
2 实现
